name: allure-ui

on: [push, workflow_dispatch]

env:
  AZURE_WEBAPP_PACKAGE_PATH: "published"
  ARTIFACT_NAME: "allure-ui"

jobs:
    
  generate:
    name: Generate Report  
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run allure
        working-directory: ./
        run: |
            cd Tools/allure-commandline-2.17.3/allure-2.17.3/bin
            ./allure.bat generate "../../../../Source/ReportSource/cypress-test/" -o "../../../../Source/Report Content/cypress-test/" 
            dir "../../../../Source/Report Content/cypress-test/" 
            
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: allure-webapp
          publish-profile: <publishData><publishProfile profileName="allure-webapp - Web Deploy" publishMethod="MSDeploy" publishUrl="allure-webapp.scm.azurewebsites.net:443" msdeploySite="allure-webapp" userName="$allure-webapp" userPWD="kEi4XQjTyyhajJwFvp41bTaXCDcCZtPYd6kMKeWJlmWhTe12JkW5hZcme8cL" destinationAppUrl="https://allure-webapp.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="allure-webapp - FTP" publishMethod="FTP" publishUrl="ftps://waws-prod-yt1-045.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="allure-webapp\$allure-webapp" userPWD="kEi4XQjTyyhajJwFvp41bTaXCDcCZtPYd6kMKeWJlmWhTe12JkW5hZcme8cL" destinationAppUrl="https://allure-webapp.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="allure-webapp - Zip Deploy" publishMethod="ZipDeploy" publishUrl="allure-webapp.scm.azurewebsites.net:443" userName="$allure-webapp" userPWD="kEi4XQjTyyhajJwFvp41bTaXCDcCZtPYd6kMKeWJlmWhTe12JkW5hZcme8cL" destinationAppUrl="https://allure-webapp.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>
          package: "Source/Report Content"
            
            
     
      
       
     
              
          
