name: Create New Allure Report
on:
    push:
        paths-ignore:
            - 'history/**'

jobs:
    
  generate:
    name: Generate Report  
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with: 
            token: ${{secrets.WORKFLOW_PAT}}
            clean: true
      
      - name: Create CommissionCheck API Report Using Allure
        working-directory: ./
        run: |
            cd Tools/allure-commandline-2.17.3/allure-2.17.3/bin
            ./allure.bat generate "../../../../Source/ReportSource/commissioncheckapi/" -o "../../../../Source/Report Content/commissioncheckapi/" 
                        
      - name: Copy CommissionCheck API History Folder
        working-directory: ./
        run: |          
            Copy-Item "./Source/Report Content/commissioncheckapi/history/*.*" -Destination "./Source/ReportSource/commissioncheckapi/history"
                
      - name: Create ValueOne Report Using Allure
        working-directory: ./
        run: |
            cd Tools/allure-commandline-2.17.3/allure-2.17.3/bin
            ./allure.bat generate "../../../../Source/ReportSource/valueone/" -o "../../../../Source/Report Content/valueone/" 
                    
      - name: Copy ValueOne History Folder
        working-directory: ./
        run: |          
            Copy-Item "./Source/Report Content/valueone/history/*.*" -Destination "./Source/ReportSource/valueone/history"
            
      - name: Commit History Folder
        working-directory: ./
        run: |             
             git config --global user.email "bhagyashree.saigal@pricemetrix.com"
             git config --global user.name "Your Name"                 
             git add ./Source/ReportSource/commissioncheckapi/history/
             git add ./Source/ReportSource/valueone/history/
             git commit -m "AUTO COMMIT - Preserving history"
             git push origin    
             
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{secrets.APP_NAME}}
          publish-profile: ${{secrets.PUBLISH_PROFILE}}
          package: "Source/Report Content"
          
            
     
      
       
     
              
          
