name: allure-ui

on: [push, workflow_dispatch]

env:
  AZURE_WEBAPP_PACKAGE_PATH: "published"
  ARTIFACT_NAME: "allure-ui"

jobs:
    
  generate:
    name: Generate Report  
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run allure
        working-directory: ./
        run: |
            cd Tools/allure-commandline-2.17.3/allure-2.17.3/bin
            allure.bat generate "../../../../Source/ReportSource/cypress-test/" -o "../../../../Source/Report Content/"             
            dir "../../../../Source/Report Content/" 
            
            
     
      
       
     
              
          
